# Site Info
title: 'data engineering study'
tagline: 'data engineering study'
description: '프로그래밍을 공부하며 배운점 느낀점을 기록하는 곳입니다.'
baseurl: ""
url: https://woolinchoi.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: CHOI WOOLIN
  description: CHOI WOOLIN
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/WoolinChoi
    facebook:  
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:    mailto:woolin06@naver.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { java: '/blog/categories/#java'}
    - { 알고리즘 문제풀이: '/blog/categories/#알고리즘-문제풀이' }
    - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: # leave blank if you don't want google analytics
disqus_short_name: # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
